name: Deploy Image Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Deploy Script On Docker Instance
      run: |
        INSTANCE_IP=${{ vars.INSTANCE_IP }}
        mkdir ~/.ssh
        touch ~/.ssh/config

        echo -n "${{ secrets.SSH_KEY }}" > ~/ssh-key.pem
        sudo chmod 600 ~/ssh-key.pem

        echo "Host target"                  >> ~/.ssh/config
        echo "  HostName $INSTANCE_IP"      >> ~/.ssh/config
        echo "  User ubuntu"                >> ~/.ssh/config
        echo "  IdentityFile ~/ssh-key.pem" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no"   >> ~/.ssh/config

        ssh target "bash ~/deploy.sh ${{ vars.docker_username }} ${{ secrets.docker_password }} ${{ vars.docker_repository }} ${{ github.event.inputs.tag }}"
