name: Deploy Image Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/config

        echo -n "${{ secrets.SSH_KEY }}" > ~/ssh-key.pem
        sudo chmod 600 ~/ssh-key.pem

        echo "Host target"                        >> ~/.ssh/config
        echo "  HostName ${{ vars.INSTANCE_IP }}" >> ~/.ssh/config
        echo "  User ubuntu"                      >> ~/.ssh/config
        echo "  IdentityFile ~/ssh-key.pem"       >> ~/.ssh/config
        echo "  StrictHostKeyChecking no"         >> ~/.ssh/config

        ssh target docker ps
        ssh target "bash ~/deploy.sh ${{ vars.docker_username }} ${{ secrets.docker_password }} ${{ vars.docker_repository }} ${{ github.event.inputs.tag }}"
