name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      # name:
      #   type: choice
      #   description: Who to greet
      #   options: 
      #   - monalisa
      #   - cschleiden
      # message:
      #   required: true
      # use-emoji:
      #   type: boolean
      #   description: Include 🎉🤣 emojis
      # environment:
      #   type: environment
      tag:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        tag_to_deploy=${{ github.event.inputs.tag }}
        echo "deploying $tag_to_deploy"
        
        INSTANCE_IP=${{ vars.INSTANCE_IP }}
        SSH_KEY=${{ secrets.SSH_KEY }}

        mkdir ~/.ssh
        touch ~/.ssh/config

        echo "$SSH_KEY" > ~/ssh-key.pem

        echo "Host target"                  >> ~/.ssh/config
        echo "  HostName $INSTANCE_IP"      >> ~/.ssh/config
        echo "  User ubuntu"                >> ~/.ssh/config
        echo "  IdentityFile ~/ssh-key.pem" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no"   >> ~/.ssh/config

        ssh target docker ps
