name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release Type
        options: 
        - major
        - minor
        - patch
  pull_request:
    types: [closed]

jobs:
  pr-merge-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Merge Message
        run: echo "${{ github.event.inputs.name }}"
